version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://rustuser:admin@postgres:5432/bitcoin_explorer
      API_KEY: BQYsYLkf8Ex8wnDtHEjXAyiEOuQjKip3
      BITQUERY_API_TOKEN: ory_at_55ZiBufdk_dMMfVZxIgA-8jAGVxM6DCcm3roWg6RUN0.KnYKonzq1j3eufdH9gH_2jRDxmM2lRGdojNW5nU3aac
    networks:
      - app-network

  frontend:
    build: 
      context: ./bitcoin-explorer-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:13.15
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bitcoin_explorer
      POSTGRES_USER: rustuser
      POSTGRES_PASSWORD: admin
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rustuser"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
